### ISSUE TITLE
坐等大哥更新啊，valine到1.5版本了，用的hexo frame主题不知道怎么添加这个画板

### ISSUE THREAD

**Issue by tomyu168** [flatblowfish/cave-draw#2]
看不太明白怎么添加，是head.ejs嘛

**Comment by flatblowfish** [comment]
原理很简单，就是把canvas转成字符串附加到评论框中。所以跟什么博客框架、主题没有关系。
只是有的评论系统不允许提交base64格式的图片，需要允许。

**Comment by flatblowfish** [comment]
hexo不要更改主题。在`source\_data\footer.swig`添加下面的代码即可。

```html
<script src="https://cdn.jsdelivr.net/gh/flatblowfish/cave-draw/dist/cave-draw.min.js"></script>

// 发现有Valine就初始化CaveDraw
var count = 0;
var dom_timer = setInterval(function () {
	if (++count > 50) clearInterval(dom_timer);
	if (document.querySelector('#veditor')) {
		var cdraw = new CaveDraw({
			element: "#veditor",
			readOnlyMode: false, // valine 不提交form，而是过滤评论框数据后发送，所以评论框不能readonly。
			afterUpdateEditor: ()=>{ // 手动触发valine对评论框数据的过滤
				document.querySelector('#veditor').focus();
				document.querySelector('#veditor').blur();
			},
			controls: ['brush', 'eraser', 'bucket', 'clear', 'undo', 'redo', 'save']
		});
		clearInterval(dom_timer);
	}
}, 200);
```

**Comment by flatblowfish** [comment]
Valine不开源，有空再更新。

**Comment by flatblowfish** [comment]
**刚刚测了一下，最新版本的Valine v1.5.1，支持base64格式的图片提交了。**
不需要任何hack。

**Comment by tomyu168** [comment]
> hexo不要更改主题。在`source\_data\footer.swig`添加下面的代码即可。
> 
> ```js
> <script src="https://cdn.jsdelivr.net/gh/flatblowfish/cave-draw/dist/cave-draw.min.js"></script>
> 
> // 发现有Valine就初始化CaveDraw
> var count = 0;
> var dom_timer = setInterval(function () {
> 	if (++count > 50) clearInterval(dom_timer);
> 	if (document.querySelector('#veditor')) {
> 		var cdraw = new CaveDraw({
> 			element: "#veditor",
> 			readOnlyMode: false, // valine 不提交form，而是过滤评论框数据后发送，所以评论框不能readonly。
> 			afterUpdateEditor: ()=>{ // 手动触发valine对评论框数据的过滤
> 				document.querySelector('#veditor').focus();
> 				document.querySelector('#veditor').blur();
> 			},
> 			controls: ['brush', 'eraser', 'bucket', 'clear', 'undo', 'redo', 'save']
> 		});
> 		clearInterval(dom_timer);
> 	}
> }, 200);
> ```
感谢，已添加成功，现在遇到一个小问题就是，valine评论先得打几个字，不然如果先开画板，那个评论框会自动拉长得特别厉害

![image](https://user-images.githubusercontent.com/35031186/206972158-e0e051ef-420b-4f3c-b1ea-b8b573ff4b44.png)

**Comment by tomyu168** [comment]
哦好像评论一次，后面就没这个问题了

**Comment by flatblowfish** [comment]
> 哦好像评论一次，后面就没这个问题了

你看我部署的demo站点，[https://flatblowfish.github.io/cave-draw/](https://flatblowfish.github.io/cave-draw/)，是没有这个问题的。

你右键查看页面源码，就会看到这样一段css。
```css
.v[data-class="v"] .veditor {
	max-height: 17em;
}
```
这就控制了Valine评论框的最大高度。

**Comment by flatblowfish** [comment]
这个画板是可以应用到所有评论系统的，所以不可能每个评论系统都写个插件来适配。
这种小修改，是需要用户自己DIY的。
比如，我就是要在Valine评论里写作文，然后再画幅画，那么，你可以写点儿js判断画板是否打开，来设置评论框高度。
或者继续加上一点儿css。
```css
.v[data-class="v"] .veditor {
	overflow-y: scroll;
}
```

**Comment by Heithon** [comment]
大佬你好，我也用的hexo。我在head里面用script标签插入了代码，但是画板在整个评论框的下面，提交也提交不了，求教怎么解决

![image](https://user-images.githubusercontent.com/85172139/207017026-07799ea1-4a97-4010-b4a8-8ae649616bcc.png)

head里的代码引用：
![image](https://user-images.githubusercontent.com/85172139/207017150-1e1c0914-4c38-4d54-8dd1-7d1aed893f30.png)
![image](https://user-images.githubusercontent.com/85172139/207017228-c1a041ed-33a0-4811-a4f9-9b7f618607f3.png)

**Comment by flatblowfish** [comment]
```css
/* 设置评论框高度 */
.v[data-class="v"] .veditor {
    max-height: 17em;
    overflow-y: scroll;
}

/* 去除查看更多 */
.v[data-class="v"] .vcards .vcard .vcontent.expand {
    max-height: none;
}

.v[data-class="v"] .vcards .vcard .vcontent.expand::before,
.v[data-class="v"] .vcards .vcard .vcontent.expand::after {
    display: none;
}
```
